[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = true
  framework = "vite"

[build.environment]
  VITE_API_URL = "https://motaz-backend-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
